server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

## Optional
#spring.security.oauth2.client.registration.google.client-id=${865813930936-fl24c6d9i565ecqaddkrdu1eafe96udh.apps.googleusercontent.com}
#spring.security.oauth2.client.registration.google.client-secret=${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}